export default {
    TITLE_LABEL: "TITLE",
    TIMESTAMP_LABEL: "TIMESTAMP",
    LOCATION_LABEL: "LOCATION",
    MOOD_LABEL: "MOOD",
    MUSIC_LABEL: "MUSIC",
    ENTRY_LABEL: "Write your entry here...",
    BUTTON_TEXT_SUBMIT: "SUBMIT"
}